### ISSUE TITLE
Use fmt with throttle logging functions

### ISSUE THREAD

**Issue by mr337** [facontidavide/ros2_logging_fmt#1]
My C++ is a little rough but looking at the header of this module, I don't believe the [throttle logging functions](https://docs.ros2.org/foxy/api/rclcpp/logging_8hpp.html#a53cee4093804b13f31cb1516087400eb) are currently supported.

If this is the case, would you be open to a PR to support this? I think I know how to bring that functionality in.

**Comment by facontidavide** [comment]
correct. Be my guest adding it
